### ISSUE TITLE
Let you pass Customers as the EntityRef to Expense

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/ledger_sync#92]
We currently only allow you to pass in a vendor to the expense object. QBO also lets you do customers or employees:
https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/purchase
![image](https://user-images.githubusercontent.com/4755444/67524040-cabc2080-f664-11e9-9867-fdc62bb3788e.png)

Since we only have customer right now, let's add in support for that. 
I'm not sure how you want to do this, since now it can be either the vendor or the customer that is present. Perhaps we need some concept of a polymorphic entity?

cc @ryanwjackson

**Comment by ryanwjackson** [comment]
Ok, just to make sure I understand and add some color here, we current support `expense.vendor` which the ID of gets translated to `EntityRef.value`.  I'm wondering if it makes sense to have `expense.entity` instead that accepts a `Vendor` or `Customer`.

Thoughts?

**Comment by ryanwjackson** [comment]
Doing a little digging into NS, I am not sure how we will have to handle this in the future.  If these objects are indeed the same, it seems NS has more specific objects instead of the "polymorphism" based on the entity.  For example, they have [`CustomerPayment`](https://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2019_2/schema/record/customerpayment.html) and [`VendorPayment`](https://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2019_2/schema/record/vendorpayment.html).

I say we add `expense.entity` with the ability to be a Vendor or Customer and cross the NS bridge when we get there.

If agreed, @jozefvaclavik can you do that?

**Comment by mattgmarcus** [comment]
I'm fine crossing that bridge later
